# Generated by Django 3.2.6 on 2021-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernm', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=50)),
                ('cnfpswd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='social_contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Que', models.CharField(max_length=100)),
                ('opt1', models.CharField(max_length=50)),
                ('opt2', models.CharField(max_length=50)),
                ('opt3', models.CharField(max_length=50)),
                ('opt4', models.CharField(max_length=50)),
            ],
        ),
    ]
